# Generated by Django 2.0 on 2019-05-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_jugador', models.CharField(max_length=30)),
                ('nombre_Dire', models.CharField(max_length=100)),
                ('partidos_total', models.CharField(max_length=20)),
                ('partidos_ganados', models.CharField(max_length=100)),
                ('partidos_perdidos', models.CharField(max_length=254)),
                ('partidso_empate', models.CharField(max_length=254)),
                ('puntos', models.CharField(max_length=254)),
                #('posicion', models.CharField(max_length=254)),
                #('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=100)),

            ],
            options={
                'db_table': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='Fut2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('edad', models.CharField(max_length=100)),
                ('numero_juga', models.CharField(max_length=254)),
                ('id_equipo', models.CharField(max_length=254)),
                #('contacto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'jugadores',
            },
            ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidos_total', models.CharField(max_length=20)),
                ('partidos_ganados', models.CharField(max_length=100)),
                ('partidos_perdidos', models.CharField(max_length=254)),
                ('partidso_empate', models.CharField(max_length=254)),
                ('puntos', models.CharField(max_length=254)),
                ('id_equipo', models.CharField(max_length=254)),
                #('contacto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'partidos',
            },
        ),

        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('edad', models.CharField(max_length=100)),
                ('id_equipo_a', models.CharField(max_length=254)),
                ('id_equipo_b', models.CharField(max_length=254)),
                ('infracciones', models.CharField(max_length=254)),
                #('contacto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'arbitros',
            },
            )
    ]
